server:
    port: 9081
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: web-manager
    boot:
        admin:
            url: http://localhost:9999
            context-path: /monitorui
endpoints:
    health:
        sensitive: false

security:
    oauth2:
        client:
            client-id: acme
            client-secret: acmesecret
            scope: read,write
            auto-approve-scopes: '.*'
        authorization:
            checkTokenAccess: isAuthenticated()
            
jfish:
    security:
        syncPermissionData: true
        csrf:
            disable: true
        logoutUrl: /logout
siteConfig:
    uploadImageAccessPath: http://localhost/img/manager
    upload:
        #storeType: ftp
        #ftpServer: 127.0.0.1
        #ftpUser: test
        #ftpPassword: test
        fileStorePath: G:/temp/upload_files
        appContextDir: manager
        #maxUploadSize: 1024
