spring:
    profiles:
        active: dev
    freemarker:
        suffix: .html
jfish: 
    profile: true
    mvc: 
        mediaTypes:
            json: application/json
            xls: application/vnd.ms-excel
            xml: application/xml
        negotiating-view: true
siteConfig:
    name: 后台管理系统
    config:
        security:
            preventXssRequest: true