server:
    port: 9080
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: onetwo-oauth2-resource
    boot:
        admin:
            url: http://localhost:9999
            context-path: /monitorui
security:
    oauth2:
        client:
            client-id: acme
            client-secret: acmesecret
            access-token-uri: http://localhost:8080/oauth/token
            user-authorization-uri: http://localhost:8080/oauth/authorize
        resource:
            user-info-uri: http://localhost:8080/me
